
#define TRIAL_VALUE_UNDEFINED										0
#define TRIAL_VALUE_DEFINED											1
#define TRIAL_VALUE_DEFINED_CANNOT_EXCLUDED							2
#define TRIAL_VALUE_DEFINED_CAN_EXCLUDED_ONLY_BY_MINSQLIN			3

#define TRIAL_VALUE_INCLUDED										11
#define TRIAL_VALUE_INCLUDED_TO_MINSQLIN							13


#define TRIAL_VALUE_EXCLUDED										20

#define TRIAL_VALUE_EXCLUDED_BY_MINSQLIN							23
#define TRIAL_VALUE_EXCLUDED_AS_CONNECTED							24
