/*****************************************************************************/
/*                                                                           */
/*             INTERACTIVE PROGRAM FOR FORWARD EBP NETS MANAGEMENT           */
/*                                                                           */
/*****************************************************************************/

# include <stdio.h>
# include <stdlib.h>
#include <string.h>
#include <malloc.h>
#include <ctype.h>

# include "NRLib.h"

# define NULLO 0

/*************************** MAIN ******************************************/


int main(int argc, char *argv[])
{
	NRLib nrlib;
	return nrlib.main(argc, argv);
}






