//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Graphs.rc
//
#define IDC_WAV_DISP                    3
#define IDC_WAV_EPSILON                 4
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_PARAM                       102
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_WAVPARAM_TMPL               105
#define IDR_MAINFRAME                   128
#define IDR_GRAPHSTYPE                  129
#define IDR_OGTYPE                      130
#define IDD_PARAM2                      131
#define IDD_PROP                        132
#define IDD_WAV_PARAM                   133
#define IDC_TIME                        1000
#define IDC_TIME1                       1001
#define IDC_TIME2                       1002
#define IDC_SETTIME                     1003
#define IDC_SIGNAL                      1004
#define IDC_SIGNAL1                     1005
#define IDC_SIGNAL2                     1006
#define IDC_COMBO1                      1006
#define IDC_COMBO_WAV_TYPE              1006
#define IDC_ADDSIGNAL                   1007
#define IDC_ADDSIGNAL1                  1007
#define IDC_SPIN1                       1007
#define IDC_COMBO_WAV_ORDER             1007
#define IDC_ALPHA                       1008
#define IDC_EDIT1                       1008
#define IDC_COMBO_WAV_MAXLEVEL          1008
#define IDC_BETA                        1009
#define IDC_LIST_WAV_TYPE               1009
#define IDC_EPSILON                     1010
#define IDC_LIST_WAV_ORDER              1010
#define IDC_STATIC_WAV_LEN              1010
#define IDC_APPLY                       1011
#define IDC_EDIT_WAV_EPSILON            1011
#define IDC_ERROR                       1012
#define IDC_RADIO_WAV1                  1012
#define IDC_RADIO_WAV2                  1013
#define IDC_ALPHADET                    1013
#define IDC_FUNDET                      1014
#define IDC_MAXORDER                    1015
#define IDC_BUTTONALPHA                 1016
#define IDC_APPLY2                      1017
#define IDC_TIME3                       1018
#define IDC_ERROR2                      1019
#define IDC_OUTLAG                      1020
#define IDC_SETTIMEEND                  1021
#define IDC_ANALIT_STRING               1022
#define IDC_ANALIT_SAVE                 1023
#define IDC_ADDSIGNAL2                  1024
#define IDC_AMBIENT                     1100
#define IDC_DIFFUSE                     1101
#define IDC_SPECULAR                    1102
#define IDC_AMB_TEXT                    1103
#define IDC_DIFFUSE_TEXT                1104
#define IDC_SPECULAR_TEXT               1105
#define IDC_XPOS                        1106
#define IDC_XPOS_TEXT                   1107
#define IDC_YPOS                        1108
#define IDC_YPOS_TEXT                   1109
#define IDC_ZPOS                        1110
#define IDC_ZPOS_TEXT                   1111
#define IDC_AMBMAT                      1112
#define IDC_AMBMAT_TEXT                 1113
#define IDC_DIFFMAT                     1114
#define IDC_DIFFMAT_TEXT                1115
#define IDC_SPECMAT                     1116
#define IDC_SPECMAT_TEXT                1117
#define IDC_FILENAME                    1118
#define IDC_SHINE                       1119
#define IDC_SHINE_TEXT                  1120
#define IDC_EMISSION                    1121
#define IDC_EMISSION_TEXT               1122
#define IDC_AMBMAT2                     1123
#define IDC_AMBMAT_TEXT2                1124
#define IDC_DIFFMAT2                    1125
#define IDC_DIFFMAT_TEXT2               1126
#define IDC_SPECMAT2                    1127
#define IDC_SPECMAT_TEXT2               1128
#define IDC_AMBMAT3                     1129
#define IDC_AMBMAT_TEXT3                1130
#define IDC_DIFFMAT3                    1131
#define IDC_DIFFMAT_TEXT3               1132
#define IDC_SPECMAT3                    1133
#define IDC_SPECMAT_TEXT3               1134
#define IDC_AMBMAT4                     1135
#define IDC_AMBMAT_TEXT4                1136
#define IDC_DIFFMAT4                    1137
#define IDC_DIFFMAT_TEXT4               1138
#define IDC_SPECMAT4                    1139
#define IDC_SPECMAT_TEXT4               1140
#define ID_FILE_IMPORT                  32772
#define ID_FILE_EXPORT                  32773
#define ID_EDIT_PARAMETRS               32774
#define ID_FILE_IMPORT2                 32775
#define ID_FILE_EXPORT2                 32776
#define ID_SERVISE_COVARIATION          32777
#define ID_EDIT_PROPERTIES              32778
#define ID_EDIT_BACKGROUND              32779
#define ID_VIEW_FILL                    32780
#define ID_VIEW_QUAD                    32781
#define ID_READ_DATA                    32782
#define ID_FILE_NEW2D                   32783
#define ID_FILE_NEW_2D                  32783
#define ID_FILE_NEW_3D                  32784
#define ID_ANIMATE_GRAPHIC              32785
#define ID_ANIMATE_STOP                 32786
#define ID_SERVISE_ANALIZECOV           32787
#define ID_COM_CONNECT                  32788
#define ID_COM_READ                     32789
#define ID_COM_DISCONNECT               32790
#define ID_SERVISE_WAVELET              32791
#define ID_COM_SET_FILENAME             32792

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
